// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_id_ from "./routes/[id].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_comics_id_ from "./routes/api/comics/[id].ts";
import * as $api_comics_index from "./routes/api/comics/index.ts";
import * as $api_comics_random from "./routes/api/comics/random.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $characters from "./routes/characters.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $ComicDisplay from "./islands/ComicDisplay.tsx";
import * as $ComicNav from "./islands/ComicNav.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Nav from "./islands/Nav.tsx";
import * as $NavItem from "./islands/NavItem.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[id].tsx": $_id_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/comics/[id].ts": $api_comics_id_,
    "./routes/api/comics/index.ts": $api_comics_index,
    "./routes/api/comics/random.ts": $api_comics_random,
    "./routes/api/joke.ts": $api_joke,
    "./routes/characters.tsx": $characters,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ComicDisplay.tsx": $ComicDisplay,
    "./islands/ComicNav.tsx": $ComicNav,
    "./islands/Counter.tsx": $Counter,
    "./islands/Nav.tsx": $Nav,
    "./islands/NavItem.tsx": $NavItem,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
